CREATE TABLE IF NOT EXISTS course_images (
  id uuid PRIMARY KEY REFERENCES auth.users ON DELETE CASCADE,
  course_id uuid REFERENCES courses(id) ON DELETE CASCADE,
  image_url TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
